name: kt_drawer_menu
description: KTDrawer is a library for flutter to create a beautiful drawer menu with with deep customization capabilities.
version: 0.0.2
homepage: https://github.com/tuankhaiit/KTDrawer
repository: https://github.com/tuankhaiit/KTDrawer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
